---
- name: Install the Promtail on PreProd servers
  hosts: preprod
  tasks:
    - name: Loki Promtail | Download distribution
      get_url:
        url: "https://github.com/grafana/loki/releases/download/v1.2.0/promtail-linux-amd64.zip"
        dest: "/app/logs/lokigrafana/promtail-linux-amd64.zip"
      become: yes
      become_user: username
      
    - name: Loki Promtail | unpack distribution
      unarchive:
        src: "/app/logs/lokigrafana/promtail-linux-amd64.zip"
        dest: "/app/logs/lokigrafana/"
        remote_src: yes
      become: yes 
      
    - name: Loki | Specify permissions
      file:
        dest: "/app/logs/lokigrafana/promtail-linux-amd64"
        mode: "u=rwx,g=rx,o=rx"
        owner: "username"
        group: "username"
      become: yes
